### PR TITLE
Support latest Spigot versions

### PR DESCRIPTION
**Pull request by uplusion23**
Added current versions, and a tag to support future versions without a need to update the build tools.

### CODE REVIEW

**Comment by MoaufmKlo** [comment]
Thanks for contributing! I'll merge this now. As I'm still having issues building the Electron app, I'll publish the compiled release once I am able to again or, if someone else can compile it for me. Cheers!

**Comment by uplusion23** [comment]
Currently at work, but I got a successful build, and I'll send you the method once I get home. I used yarn as the build tool.

**Comment by MoaufmKlo** [comment]
That'd be great! 👍

**Comment by uplusion23** [comment]
I ended up installing yarn globally, and running `yarn dist`. You may need `electron-builder` but I'm not positive.

**Pull request merged**
